In [1]:
import pandas as pd

In [2]:
data_path = 'data\\bronze\\'

In [3]:
# Carregando os DataFrames
listings_path = data_path + 'listings_bronze.parquet'
calendar_path = data_path + 'calendar_bronze.parquet'
reviews_path = data_path + 'reviews_bronze.parquet'
listings_silver = pd.read_parquet(listings_path)
calendar_silver = pd.read_parquet(calendar_path)
reviews_silver = pd.read_parquet(reviews_path)

In [4]:
listings_rows, listings_cols = listings_silver.shape
calendar_rows, calendar_cols = calendar_silver.shape
reviews_rows, reviews_cols = reviews_silver.shape
print(
    f'''
Listings: Linhas: {listings_rows}, Colunas {listings_cols}
Calendar: Linhas: {calendar_rows}, Colunas {calendar_cols}
Reviews: Linhas: {reviews_rows}, Colunas {reviews_cols}
    '''
)

Listings: Linhas: 34664, Colunas 75
Calendar: Linhas: 12652371, Colunas 7
Reviews: Linhas: 773134, Colunas 6

In [11]:
listings_silver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34664 entries, 0 to 34663
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            34664 non-null  int64
 1   listing_url                                   34664 non-null  object
 2   scrape_id                                     34664 non-null  int64
 3   last_scraped                                  34664 non-null  object
 4   source                                        34664 non-null  object
 5   name                                          34664 non-null  object
 6   description                                   33501 non-null  object
 7   neighborhood_overview                         17016 non-null  object
 8   picture_url                                   34664 non-null  object
 9   host_id                                       34664 non-null  int64
 10  host_url                                      34664 non-null  object
 11  host_name                                     34664 non-null  object
 12  host_since                                    34664 non-null  object
 13  host_location                                 27869 non-null  object
 14  host_about                                    16551 non-null  object
 15  host_response_time                            28879 non-null  object
 16  host_response_rate                            28879 non-null  object
 17  host_acceptance_rate                          31089 non-null  object
 18  host_is_superhost                             33796 non-null  object
 19  host_thumbnail_url                            34664 non-null  object
 20  host_picture_url                              34664 non-null  object
 21  host_neighbourhood                            28779 non-null  object
 22  host_listings_count                           34664 non-null  int64
 23  host_total_listings_count                     34664 non-null  int64
 24  host_verifications                            34664 non-null  object
 25  host_has_profile_pic                          34664 non-null  object
 26  host_identity_verified                        34664 non-null  object
 27  neighbourhood                                 17016 non-null  object
 28  neighbourhood_cleansed                        34664 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      34664 non-null  float64
 31  longitude                                     34664 non-null  float64
 32  property_type                                 34664 non-null  object
 33  room_type                                     34664 non-null  object
 34  accommodates                                  34664 non-null  int64
 35  bathrooms                                     33824 non-null  float64
 36  bathrooms_text                                34623 non-null  object
 37  bedrooms                                      34526 non-null  float64
 38  beds                                          33822 non-null  float64
 39  amenities                                     34664 non-null  object
 40  price                                         33692 non-null  object
 41  minimum_nights                                34664 non-null  int64
 42  maximum_nights                                34664 non-null  int64
 43  minimum_minimum_nights                        34664 non-null  int64
 44  maximum_minimum_nights                        34664 non-null  int64
 45  minimum_maximum_nights                        34664 non-null  int64
 46  maximum_maximum_nights                        34664 non-null  int64
 47  minimum_nights_avg_ntm                        34664 non-null  float64
 48  maximum_nights_avg_ntm                        34664 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              34327 non-null  object
 51  availability_30                               34664 non-null  int64
 52  availability_60                               34664 non-null  int64
 53  availability_90                               34664 non-null  int64
 54  availability_365                              34664 non-null  int64
 55  calendar_last_scraped                         34664 non-null  object
 56  number_of_reviews                             34664 non-null  int64
 57  number_of_reviews_ltm                         34664 non-null  int64
 58  number_of_reviews_l30d                        34664 non-null  int64
 59  first_review                                  26218 non-null  object
 60  last_review                                   26218 non-null  object
 61  review_scores_rating                          26218 non-null  float64
 62  review_scores_accuracy                        26209 non-null  float64
 63  review_scores_cleanliness                     26209 non-null  float64
 64  review_scores_checkin                         26209 non-null  float64
 65  review_scores_communication                   26209 non-null  float64
 66  review_scores_location                        26209 non-null  float64
 67  review_scores_value                           26207 non-null  float64
 68  license                                       0 non-null      float64
 69  instant_bookable                              34664 non-null  object
 70  calculated_host_listings_count                34664 non-null  int64
 71  calculated_host_listings_count_entire_homes   34664 non-null  int64
 72  calculated_host_listings_count_private_rooms  34664 non-null  int64
 73  calculated_host_listings_count_shared_rooms   34664 non-null  int64
 74  reviews_per_month                             26218 non-null  float64
dtypes: float64(18), int64(23), object(34)
memory usage: 19.8+ MB

In [14]:
calendar_silver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12652371 entries, 0 to 12652370
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            object
 2   available       object
 3   price           object
 4   adjusted_price  float64
 5   minimum_nights  float64
 6   maximum_nights  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 675.7+ MB

In [15]:
reviews_silver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773134 entries, 0 to 773133
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     773134 non-null  int64
 1   id             773134 non-null  int64
 2   date           773134 non-null  object
 3   reviewer_id    773134 non-null  int64
 4   reviewer_name  773134 non-null  object
 5   comments       773110 non-null  object
dtypes: int64(3), object(3)
memory usage: 35.4+ MB

In [16]:
listings_silver.sample(10)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
21387,864581574158967899,https://www.airbnb.com/rooms/864581574158967899,20240627045056,2024-06-27,city scrape,LOFT Sofistic em Botafogo/RJ,Surround yourself with style in this exception...,None,https://a0.muscache.com/pictures/462fd103-8d92...,335634111,...,4.93,4.86,4.84,NaN,f,1,1,0,0,2.94
10024,41562792,https://www.airbnb.com/rooms/41562792,20240627045056,2024-06-28,city scrape,Apto 106 - Flat com estacionamento incluso.,"Our place holds 4 comfortable people, has easy...",Close to Barra beach and Recreio dos Bandeiran...,https://a0.muscache.com/pictures/624dd0fa-59b9...,327150112,...,4.90,4.70,4.83,NaN,f,1,1,0,0,3.47
19781,811631303559623497,https://www.airbnb.com/rooms/811631303559623497,20240627045056,2024-06-27,city scrape,Casa próxima a transportes,Stay well located to get to know Rio de Janeiro.,The neighborhood is relatively quiet and quiet!,https://a0.muscache.com/pictures/miso/Hosting-...,497160654,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
22249,910261209419116456,https://www.airbnb.com/rooms/910261209419116456,20240627045056,2024-06-27,city scrape,Flat frontal mar,Flat complete with all the necessary utensils ...,None,https://a0.muscache.com/pictures/miso/Hosting-...,131106900,...,4.84,5.00,4.81,NaN,t,2,2,0,0,6.34
9409,40179166,https://www.airbnb.com/rooms/40179166,20240627045056,2024-06-27,city scrape,APT COPA / IPA /ARPOADOR 2qts / GAR (OP) 50 rs,The apt is next to the Copacabana fort. <br />...,very safe.<br />Next to the fort of Copacabana...,https://a0.muscache.com/pictures/1df976eb-c5a6...,310257502,...,4.90,4.98,4.58,NaN,f,1,1,0,0,2.28
67,96478,https://www.airbnb.com/rooms/96478,20240627045056,2024-06-28,city scrape,APARTAMENT IN BOTAFOGO BEAUTIFULL,LINDO APARTAMENTO DECORADO COMO UMA CABANA COM...,"bRes,resturantes,shoping botafogo 150 meters,m...",https://a0.muscache.com/pictures/miso/Hosting-...,530471,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
25016,1010276066674304958,https://www.airbnb.com/rooms/1010276066674304958,20240627045056,2024-06-28,city scrape,Copacabana! Ótima localização!,Relax in this unique and quiet place.,None,https://a0.muscache.com/pictures/hosting/Hosti...,74652696,...,5.00,5.00,5.00,NaN,t,26,26,0,0,0.95
9344,39866230,https://www.airbnb.com/rooms/39866230,20240627045056,2024-06-27,city scrape,OCEAN VIEW-BARRA DA TIJUCA-PEDRA DE ITAÚNA RIO-RJ,COME ENJOY AND RELAX IN A CONDOMINIUM WITH EVE...,CLOSE TO THE BEST SHOPPING MALLS OF RIO AS WEL...,https://a0.muscache.com/pictures/9d2d7f38-0d03...,306990837,...,5.00,5.00,4.75,NaN,f,1,1,0,0,0.07
7457,29286451,https://www.airbnb.com/rooms/29286451,20240627045056,2024-06-28,city scrape,Apartamento em Copacabana (1 quadra da praia),My space is about 3 minutes from the world fam...,None,https://a0.muscache.com/pictures/2c607f92-43ab...,10111118,...,4.99,4.67,4.77,NaN,f,2,2,0,0,1.18
30442,1087050586102503833,https://www.airbnb.com/rooms/1087050586102503833,20240627045056,2024-06-27,city scrape,Apartamento bambu Laranjeiras,Fun with the whole family in this stylish plac...,None,https://a0.muscache.com/pictures/hosting/Hosti...,86883907,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [17]:
calendar_silver.sample(10)

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
11989399,1146564055113540362,2025-05-31,f,$169.00,NaN,1.0,365.0
6837682,784635761983716388,2025-02-16,f,$360.00,NaN,3.0,15.0
4793950,53512617,2025-02-08,t,"$1,404.00",NaN,5.0,90.0
4780063,53362351,2024-09-04,t,$200.00,NaN,2.0,30.0
9901367,1045221225385241773,2024-11-15,t,$650.00,NaN,4.0,365.0
979626,8666390,2025-03-23,f,$175.00,NaN,1.0,1125.0
5930876,695029271419447290,2025-06-06,f,$400.00,NaN,2.0,1125.0
4672861,53011419,2024-06-30,t,"$1,500.00",NaN,3.0,90.0
3489825,40428085,2025-05-07,t,$300.00,NaN,5.0,1125.0
10054000,1049472433654114183,2025-01-28,f,$141.00,NaN,1.0,90.0

In [18]:
reviews_silver.sample(10)

,listing_id,id,date,reviewer_id,reviewer_name,comments
107519,3735424,346647772,2018-11-09,1231772,George,The flat is very comfortable and in the best l...
394354,38061329,600923217,2020-02-02,83475027,Miguel,Apartamento PERFECTO en óptimas condiciones....
407716,39245266,877534704069785384,2023-04-25,137251187,Guilherme,"Tivemos ótimos dias no RJ e o apartamento, a r..."
93239,2752587,753611187196974829,2022-11-05,164813307,Gabriel,Ótimo! Recomendo.
489088,47918559,446238003927313151,2021-09-07,295851959,Jackeline,Muito receptivos e atenciosos. O apartamento t...
22696,658035,339964980,2018-10-22,152185199,Francine Karla,Apto da Claudia é uma graça! A localização é f...
641710,730370791186458590,822468749814071063,2023-02-08,59947774,Dino,Perfect place with very welcoming team and an ...
125846,5077628,539548958,2019-10-01,255782180,Marcelo Augusto,Ótima localização e receptividade!!
300164,22423770,346376677,2018-11-08,94681454,Débora,"O quarto é bem espaçoso, fresco mas possui ar ..."
445851,43425307,637318217,2020-07-12,352941160,Márcio,"Ótima localização, espaço limpo e estadia conf..."

In [28]:
listings_silver.value_counts()

Series([], Name: count, dtype: int64)

In [20]:
# Tratar nulos e duplicados

In [21]:
# Tratar Tipagem das colunas

In [ ]:
# Tratar carac

In [22]:
a = []
a.append([1,2,3,4])

In [23]:
a

[[1, 2, 3, 4]]

In [27]:
len(a)

1

In [25]:
a = [1]

In [26]:
a

[1]